
const students = [
    {
        firstName: "James",
        lastName: "Eze",
        email: "ndubuisi.eze60@univ-constantine2.dz",
        phone: "+213 798 961 871",
        address: "UV18 batiment oscar",
        city: "Constantine, nouvelle",
        password: "Blaze@500",
        inscription: "188NGA51078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G1",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "Salimane",
        lastName: "Mousaouibrahim",
        email: "Salimane.Mousaouibrahim60@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "UV18 batiment mohammed",
        city: "Alger central, Algiers",
        password: "Salimane@500",
        inscription: "188NGA52078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G2",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "OUNISSI FADOUA",
        lastName: "FADOUA",
        email: "FADOUA.OUNISSI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 4, university 2",
        city: "Constantine, nouvelle",
        password: "Ounissi@500",
        inscription: "188NGA53078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G3",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "ABADA ",
        lastName: "AYA",
        email: "AYA.ABADA@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite El-kroube",
        city: "Boumerdes, Boudouaua",
        password: "Abada@500",
        inscription: "188NGA54078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G4",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "ALLAG EDDINE AYOUB",
        lastName: "SALAH",
        email: "SALAH.EDDINE.AYOUB.ALLAG@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment salimane",
        city: "Annaba, central ville",
        password: "Allag@500",
        inscription: "188NGA55078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G5",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "HACEN",
        lastName: "ALLOUT",
        email: "HACEN.ALLOUT@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment saharawi",
        city: "Constantine, central ville",
        password: "Hacen@500",
        inscription: "188NGA56078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G6",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "MAHDI",
        lastName: "CHETTIH",
        email: "CHETTIH.MAHDI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "sans visa",
        city: "Constantine, nouvelle",
        password: "Mahdi@500",
        inscription: "188NGA57078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G7",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "Moses",
        lastName: "Amadi",
        email: "moses.amadi60@univ-constantine2.dz",
        phone: "+213 798 961 871",
        address: "UV18 batiment salfa",
        city: "Constantine, nouvelle",
        password: "Moses@500",
        inscription: "188NGA58078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G8",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "Alpha",
        lastName: "Wu-yep",
        email: "Alpha.wu-yep60@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "Alpha@500",
        inscription: "188NGA59078",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G9",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Pius",
        lastName: "Sunday",
        email: "FADOUA.OUNISSI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "UV-18 batiment oscar",
        city: "Constantine, nouvelle",
        password: "Sunday@500",
        inscription: "188NGA51008",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G10",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Boluwatife David",
        lastName: "Osuuu",
        email: "David.Osuuu@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "David@500",
        inscription: "188NGA51108",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G11",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Abdulahi",
        lastName: "Muhsin",
        email: "Muhsin.Abdulahi@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "El-harrache",
        city: "Algers, Alger central",
        password: "Abdulahi@500",
        inscription: "188NGA51208",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G12",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Babs",
        lastName: "Ibrahim",
        email: "Babs.Ibrahim@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "Babs@500",
        inscription: "188NGA51308",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G13",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Malak",
        lastName: "Menie",
        email: "Malak.Menie@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment malak",
        city: "Jelji, belle ville",
        password: "Malak@500",
        inscription: "188NGA51408",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G14",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Rahma",
        lastName: "Jacob",
        email: "Rahma.Jacob@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment Jacob",
        city: "Jelji, belle ville",
        password: "Rahma@500",
        inscription: "188NGA51508",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G15",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Sarah",
        lastName: "Bansalem",
        email: "Sarah.Bansalem@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment Bansalem",
        city: "Jelji, belle ville",
        password: "Bansalem@500",
        inscription: "188NGA51608",
        Department: "Commune Core",
        Level: "Licence 1",
        group: "G16",
        section: "Section 4",
        profile: 'student',
      },
    {
        firstName: "James",
        lastName: "Eze",
        email: "ndubuisi.eze60@univ-constantine2.dz",
        phone: "+213 798 961 871",
        address: "UV18 batiment oscar",
        city: "Constantine, nouvelle",
        password: "Blaze@500",
        inscription: "288NGA51078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G1",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "Salimane",
        lastName: "Mousaouibrahim",
        email: "Salimane.Mousaouibrahim60@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "UV18 batiment mohammed",
        city: "Alger central, Algiers",
        password: "Salimane@500",
        inscription: "288NGA52078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G2",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "OUNISSI FADOUA",
        lastName: "FADOUA",
        email: "FADOUA.OUNISSI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 4, university 2",
        city: "Constantine, nouvelle",
        password: "Ounissi@500",
        inscription: "288NGA53078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G3",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "ABADA ",
        lastName: "AYA",
        email: "AYA.ABADA@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite El-kroube",
        city: "Boumerdes, Boudouaua",
        password: "Abada@500",
        inscription: "288NGA54078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G4",
        section: "Section 1",
        profile: 'student',
      },
      {
        firstName: "ALLAG EDDINE AYOUB",
        lastName: "SALAH",
        email: "SALAH.EDDINE.AYOUB.ALLAG@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment salimane",
        city: "Annaba, central ville",
        password: "Allag@500",
        inscription: "288NGA55078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G5",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "HACEN",
        lastName: "ALLOUT",
        email: "HACEN.ALLOUT@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment saharawi",
        city: "Constantine, central ville",
        password: "Hacen@500",
        inscription: "288NGA56078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G6",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "MAHDI",
        lastName: "CHETTIH",
        email: "CHETTIH.MAHDI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "sans visa",
        city: "Constantine, nouvelle",
        password: "Mahdi@500",
        inscription: "288NGA57078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G7",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "Moses",
        lastName: "Amadi",
        email: "moses.amadi60@univ-constantine2.dz",
        phone: "+213 798 961 871",
        address: "UV18 batiment salfa",
        city: "Constantine, nouvelle",
        password: "Moses@500",
        inscription: "288NGA58078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G8",
        section: "Section 2",
        profile: 'student',
      },
      {
        firstName: "Alpha",
        lastName: "Wu-yep",
        email: "Alpha.wu-yep60@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "Alpha@500",
        inscription: "288NGA59078",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G9",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Pius",
        lastName: "Sunday",
        email: "FADOUA.OUNISSI@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "UV-18 batiment oscar",
        city: "Constantine, nouvelle",
        password: "Sunday@500",
        inscription: "288NGA51008",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G10",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Boluwatife David",
        lastName: "Osuuu",
        email: "David.Osuuu@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "David@500",
        inscription: "288NGA51108",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G11",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Abdulahi",
        lastName: "Muhsin",
        email: "Muhsin.Abdulahi@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "El-harrache",
        city: "Algers, Alger central",
        password: "Abdulahi@500",
        inscription: "288NGA51208",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G12",
        section: "Section 3",
        profile: 'student',
      },
      {
        firstName: "Babs",
        lastName: "Ibrahim",
        email: "Babs.Ibrahim@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "cite 2, university 3",
        city: "Constantine, nouvelle",
        password: "Babs@500",
        inscription: "288NGA51308",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G13",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Malak",
        lastName: "Menie",
        email: "Malak.Menie@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment malak",
        city: "Jelji, belle ville",
        password: "Malak@500",
        inscription: "288NGA51408",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G14",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Rahma",
        lastName: "Jacob",
        email: "Rahma.Jacob@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment Jacob",
        city: "Jelji, belle ville",
        password: "Rahma@500",
        inscription: "288NGA51508",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G15",
        section: "Section 4",
        profile: 'student',
      },
      {
        firstName: "Sarah",
        lastName: "Bansalem",
        email: "Sarah.Bansalem@univ-constantine2.dz",
        phone: "+213 503 961 871",
        address: "batiment Bansalem",
        city: "Jelji, belle ville",
        password: "Bansalem@500",
        inscription: "288NGA51608",
        Department: "Commune Core",
        Level: "Licence 2",
        group: "G16",
        section: "Section 4",
        profile: 'student',
      },
]




module.exports = { students };