const teacher = [
  {
    firstName: "zakarah",
    lastName: "lakar",
    email: "zakarah.lakar@univ-constantine2.dz",
    phone: "798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "lakar@500",
    department: "MI",
    module: "System Machine",
    status: "teacher",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "nabil.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "mohammed.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "musa.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "moses.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "mike.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "mark.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "emma.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "emmanuel.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "james.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "pius.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "sunday.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "bolu.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "david.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "ama.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "issac.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "lahhh.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "uthman.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "muhsin.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "ibrahim.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
  {
    firstName: "nabil",
    lastName: "bilala",
    email: "adamu.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
  },
];

module.exports = { teacher };
